SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE 
    UNION ALL
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d'), PRODUCT_ID, NULL, SALES_AMOUNT
    FROM OFFLINE_SALE 
) AS t
WHERE SUBSTRING(SALES_DATE, 1, 7) = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
