SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTRING(I.SEX_UPON_INTAKE, 1, 1) = 'I' AND (SUBSTRING(O.SEX_UPON_OUTCOME, 1, 1) IN ('S', 'N'))
